---
- hosts: all
  become: true
  become_user: root
  vars:
          link: http://www.zmanda.com/downloads/community/ZRM-MySQL/1.1/Linux/MySQL-zrm-1.1-1.noarch.rpm
          destination: /usr/src/
  tasks:
          - name: Ensure python-apt is installed
            command: >
            apt-get install python-apt -y -q
            creates=/usr/share/doc/python-apt
            
          - name:  download the mysql rpm from a remote repo
            get_url:
                    url: "{{link}}"
                    dest: "{{destination}}"
          
                    
          - name: install mysql rpm  package
            yum:
                    name: /usr/src/MySQL-zrm-1.1-1.noarch.rpm                    
                    state: present
                    

